### PR TITLE
Added customizer function for lodash.mergeWith

### PR DESCRIPTION
**Pull request by Sawtaytoes**
This a pull request to add the ability to use a custom customizer function with lodash's `.mergeWith`. The goal is to add needed functionality to compensate for more-complex merges.

### CODE REVIEW

**Comment by Sawtaytoes** [comment]
Looks like I'm using some newer ES2015 destructuring that isn't available in this version of Node.js 4. I will modify this to explicitly list out the variables instead.

**Comment by joshswan** [comment]
Sweet! Merging this in and I'll get it released shortly. Thanks for the PR :)

**Comment by joshswan** [comment]
Just published v1.1.0 to npm!

**Comment by Sawtaytoes** [comment]
Awesome. Tested and works! I appreciate the fast turnaround! 🥇

**Pull request merged**
